language: ruby
rvm:
  - "2.2.6"
  - "2.3.2"
env:
  - DB=postgresql
addons:
  postgresql: "9.4"
script:
  - rubocop
  - RAILS_ENV=test bundle exec rake --trace db:setup db:migrate spec
before_script:
  - mysql -e 'CREATE DATABASE dummy_test;' -uroot
  - psql -c 'CREATE DATABASE dummy_test;' -U postgres
