language: ruby
cache: bundler
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
gemfile:
  - gemfiles/Gemfile.rails-5.0.6
  - gemfiles/Gemfile.rails-5.1.5
  - gemfiles/Gemfile.rails-5.2-stable
env:
  global:
    - DB=postgresql
    - CC_TEST_REPORTER_ID=a726345933825a3e95f72dcfd646929ecb76eb02c7f7dcd5c28b8c7246167e26
addons:
  postgresql: "9.6"
script:
  - bundle exec rubocop
  - RAILS_ENV=test bundle exec rake --trace db:setup db:migrate spec
before_script:
  - mysql -e 'CREATE DATABASE dummy_test;' -uroot
  - psql -c 'CREATE DATABASE dummy_test;' -U postgres
  # setup code climate test coverage
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
